Update faq-troubleshooting.md
cross-seed/cross-seed.org pull request #63
Opened 2024-12-07 18:41 UTC by convexshiba

add entry for how to debug why torrents are not "suitable for search"

2024-12-10 04:34 UTC, zakkarry requested changes

2024-12-10 04:34 UTC, zakkarry commented on docs/basics/faq-troubleshooting.md
> +`includeNonVideos`. Check verbose log in app config folder for `[prefilter]` entries.
```suggestion
### Why are some torrents not suitable for searching?

Seeing a difference in total torrent count and suitable torrents (as well as
unique searches) is expected behavior. This is usually due to `config.js`
settings such as `includeSingleEpisodes`or `includeNonVideos`, `exclude` options
based on age or last date of search, or duplicate search queries which have been
reduced down to a single query.

:::tip

You can check the verbose log in the log directory of the app config folder for
`[prefilter]` entries immediately before a search starts for exact details.

:::
```

I know this is a pretty dramatic elaboration/rework, but let me know what you think and we can work from here. 

Also, not entirely sure placing this at the very end is where I'd put it, but we can worry about the placement later (I try and keep super common things more near the top) - and this seems more common than the very end. But I understand why you placed it there lol.

2024-12-11 00:21 UTC, convexshiba reviewed
adopt suggestions

2024-12-11 00:22 UTC, zakkarry commented
> adopt suggestions

Any opinion on placement more near the top?

2024-12-11 00:30 UTC, convexshiba commented
Nah not at all.

2024-12-11 00:31 UTC, convexshiba reviewed
order

2024-12-11 00:34 UTC, zakkarry commented
thanks

2024-12-11 00:34 UTC, zakkarry approved these changes

2024-12-11 00:35 UTC, merged